version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/action"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    groups:
      security:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"
