name: Filen Photo Organizer
description: Organize photos in filen.io drive
inputs:
  email:
    description: 'User login email'
    required: true
  password:
    description: 'User login passwort'
    required: true
  twoFactorCode:
    description: 'Two factor secret (if enabled)'
    required: false
  rootPath:
    description: 'Path to the photo directory'
    required: true
  dirPattern:
    description: 'Date pattern to sort the photos into (if empty, no directories will be created)'
    default: 'yyyy-MM'
  filePattern:
    description: 'Date pattern for renaming the files based on date taken (if empty, preserve original file name)'
    default: 'yyyy-MM-dd_HH.mm.ss'
  fallbackTimeZone:
    description: 'Time zone to assume for photo organization when no GPS metadata is available, i.e. the time zone in which the photos were taken, as TZ / IANA identifier'
    default: 'Europe/Berlin'
  dryRun:
    description: 'Do not perform write operations on the filen.io'
    default: false
runs:
  using: node20
  main: 'action/dist/index.js'
branding:
  icon: image
  color: white
